### ISSUE TITLE
plugin submission

### ISSUE THREAD

**Issue by orthagh** [kedson42/gestaohoras#1]
Hello, i just receveid the submission of xml for this plugin.

Please, before acceptation, fix theses issues : 

- add a logo and link it he xml
- Add at least a real EN description and move your current to a pt_br node
- Add some screenshots in dedicated nodes

Regards

**Comment by kedson42** [comment]
Done. Can you check it?
https://github.com/kedson42/gestaohoras/blob/master/gestaohoras.xml

**Comment by kedson42** [comment]
Hi, Alexandre!
Thanks for the reply. Can you check if its ok now?

https://github.com/kedson42/gestaohoras/blob/master/gestaohoras.xml

Em qui., 23 de abr. de 2020 às 03:54, Alexandre Delaunay <
notifications@github.com> escreveu:

**Comment by orthagh** [comment]
Thank you.
The plugin will be added today
