### ISSUE TITLE
Duvida;

### ISSUE THREAD

**Issue by leoinfra** [kedson42/gestaohoras#2]
Primeiro Parabéns pelo Trabalho!

Tenho um cliente e ele me  comprou 100 horas mês.  então lanço todos os chamados la. como eu computo no plugin essas 100 horas ?

**Comment by kedson42** [comment]
Obrigado!

Basta criar as tarefas no chamado informando a duração de cada uma.
O plugin soma a duração de todas as tarefas e debita do saldo do grupo requerente.
