### ISSUE TITLE
Erro ao criar tabela

### ISSUE THREAD

**Issue by GilNasciment0** [kedson42/gestaohoras#3]
Esta dando o seguinte erro ao criar tentar ativar o plugin:
Error creating tables : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `glpi_plugin_gestaohoras_balances_historys` ( `i...' at line 17

Giving up

A algo que eu possa fazer para corrigir?
LGPI 9.4
Debian 10

**Comment by kedson42** [comment]
Olá @GilNasciment0 .
Tenta fazendo o download do plugin a partir [daqui](https://github.com/kedson42/gestaohoras/releases/download/beta/gestaohoras.tar.gz).

Caso não dê certo, me retorne informando sua versão de banco.
