### ISSUE TITLE
Saldo não está debitando a partir da soma das durações das tarefas do chamado 

### ISSUE THREAD

**Issue by boldrinidouglas** [kedson42/gestaohoras#4]
Parabéns pelo projeto.
Versão do GLPI  >> 9.5.3
Todas configurações como recomendado, porém não aparecem no estrado os chamados fechados com a duração a partir das soma das durações das tarefas.
Pode ser alguma imcompatibilidade com a versão?

**Comment by kedson42** [comment]
Oi Douglas.
Exatamente. O plugin foi compatibilizado apenas com as 9.3 e 9.4

**Comment by CamiaLukenia** [comment]
Boas Kedson!
Instalei a versão 9.4 e estou com o mesmo problema. Após o encerramento do chamado não aparece no extrato o débito com a soma da duração das tarefas.
